# Creating NumPy Arrays

In [1]:
import numpy as np

In [2]:
# create an array from integer python list
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [3]:
# create an array of  float  from python list 
np.array([2.5, 3.0, 5, 8])


array([ 2.5,  3. ,  5. ,  8. ])

In [5]:
# create an array of float32 data type 
np.array([1, 2, 3, 4, 5], dtype='float32')

array([ 1.,  2.,  3.,  4.,  5.], dtype=float32)

In [6]:
# create an multi-dimensional array from nested lists
np.array([range(i, i+3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [7]:
# create a length-10 integer array with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
# create a 4x4 floating-point array filled with ones
np.ones((4,4), dtype=float)

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [9]:
# create a 4x4 array filled with 5
np.full((4,4), 5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [10]:
# create an array from linear sequence with stepping.(starts from 0, ends in 20, step 3)
np.arange(0, 20, 3) 

array([ 0,  3,  6,  9, 12, 15, 18])

In [11]:
# create a 3x3 array of uniformly distributed(values between 0-1)
np.random.random((3,3))

array([[ 0.32034246,  0.73303834,  0.64138151],
       [ 0.16098257,  0.81987617,  0.9669414 ],
       [ 0.67170316,  0.98803031,  0.29762363]])

In [12]:
# create an array of 4 values evenly spaced between 0 and 1
np.linspace(0, 1, 4)

array([ 0.        ,  0.33333333,  0.66666667,  1.        ])

In [13]:
# create a 3x3 array filled with zeros
np.zeros((3,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [14]:
# create a 3x3 array of uniformly distributed. Means:1, standard deviation 2
np.random.normal(1, 2, (3,3))

array([[-1.11885906,  3.09960863,  0.41922093],
       [ 4.25931087,  0.1487802 ,  2.3330549 ],
       [-0.48359371,  2.22875895,  0.83412693]])

In [15]:
# create a 3x3 array of random integers in between 0 and 10
np.random.randint(0, 10, (3,3))

array([[4, 9, 5],
       [9, 5, 1],
       [7, 8, 6]])

In [16]:
# create a 3x3 identity matrix
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [17]:
# create an array floating-points number between 0 and 10
np.arange(0, 10, 1, dtype=np.float32)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.], dtype=float32)