# NumPy Array Attributes

In [1]:
import numpy as np

In [4]:
# create one-dimensional array which size is 6
x1 = np.random.randint(10, size=6)

In [5]:
# create two-dimensional array which dimension is 3x4
x2 = np.random.randint(10, size=(3,4))


In [6]:
# create three-dimensional array which dimension is 3x4x5
x3 = np.random.randint(10, size=(3,4,5))

In [7]:
print("x3 ndim: ", x3.ndim) # the number of dimensions
print("x3 shape: ", x3.shape) # the size of each dimension
print("x3 size: ", x3.size) # the total size of the array

x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60


In [8]:
# print data type of array
print("dtype of x3: ", x3.dtype)
print("dtype of x2: ", x2.dtype)
print("dtype of x1: ", x1.dtype)

dtype of x3:  int64
dtype of x2:  int64
dtype of x1:  int64


In [9]:
# print the item size and total size of array(sizes in bytes)
print("item size of x3: ", x3.itemsize)
print("item size of x2: ", x2.itemsize)
print("item size of x1: ", x1.itemsize)

print("total size of x3: ", x3.nbytes)
print("total size of x2: ", x2.nbytes)
print("total size of x1: ", x1.nbytes)


item size of x3:  8
item size of x2:  8
item size of x1:  8
total size of x3:  480
total size of x2:  96
total size of x1:  48


In [10]:
# indexing in arrays
x2[0,0]

1

In [11]:
x2

array([[1, 2, 7, 6],
       [0, 5, 1, 9],
       [5, 6, 7, 6]])

In [12]:
x2[2, -1]

6

In [13]:
# modifying array
x2[2, -1] = 3
x2[2, -1]

3

In [16]:
# one-dimensional array slicing operations
print("One-Dimensional Array: ", x1)
print("First five elements: ", x1[:5]) 
print("Elements after index 5: ", x1[5:]) 
print("Middle subarray: ", x1[3:5] )
print("Every other elements: ", x1[::2]) 
print("Every other element start at index 1: ", x1[1::2])
print("All elements: ", x1[::-1])
print("Reversed every other from index 5: ", x1[5::-2])

One-Dimensional Array:  [0 3 8 7 5 7]
First five elements:  [0 3 8 7 5]
Elements after index 5:  [7]
Middle subarray:  [7 5]
Every other elements:  [0 8 5]
Every other element start at index 1:  [3 7 7]
All elements:  [7 5 7 8 3 0]
Reversed everty other from index 5:  [7 7 3]


In [17]:
# multi-dimensional array slicing operations
print("Multi-Dimensional Array: ", x2)
print("Two rows, three columns: ", x2[:2, :3])
print("All rows, every other column: ", x2[:3, ::2])
print("Reversed rows and columns: ", x2[::-1, ::-1])
print("First column of x2: ", x2[:, 0])
print("First row of x2: ", x2[0, :])
print("First row of x2: ", x2[0])

Multi-Dimensional Array:  [[1 2 7 6]
 [0 5 1 9]
 [5 6 7 3]]
Two rows, three columns:  [[1 2 7]
 [0 5 1]]
All rows, every other column:  [[1 7]
 [0 1]
 [5 7]]
Reversed rows and columns:  [[3 7 6 5]
 [9 1 5 0]
 [6 7 2 1]]
First column of x2:  [1 0 5]
First row of x2:  [1 2 7 6]
First row of x2:  [1 2 7 6]


In [18]:
# creating copy of array
x2_copy = x2[:2, :2].copy()
print(x2_copy)

[[1 2]
 [0 5]]


In [21]:
# reshape an array via np.arange()
a = np.arange(1,10).reshape((3,3))
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [23]:
# row vector via reshape
x = np.array([1,2,3])
x.reshape((1,3))

array([[1, 2, 3]])

In [24]:
# row vector via newaxis
x[np.newaxis, :]

array([[1, 2, 3]])

In [25]:
# column vector via reshape
x.reshape((3,1))

array([[1],
       [2],
       [3]])

In [26]:
# column vector via newaxis
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [35]:
# concatenate two arrays
x = np.random.randint(1,4, size=3)
y = np.random.randint(2,6, size=3)
z = np.concatenate([x,y])
print("x: ", x)
print("y: ", y)
print("concatenated x and y: ", z)

x:  [2 2 2]
y:  [4 3 5]
concatenated x and y:  [2 2 2 4 3 5]


In [36]:
# concatenate two multi-dimensional array
x = np.array([[1,2,3], [4,5,6]])
print(x)
np.concatenate([x, x])

[[1 2 3]
 [4 5 6]]


array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [37]:
# concatenate two multi-dimensional array along the first axis
print(x)
np.concatenate([x, x], axis=0)

[[1 2 3]
 [4 5 6]]


array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [38]:
# concatenate two multi-dimensional array along the second axis
print(x)
np.concatenate([x,x], axis=1)

[[1 2 3]
 [4 5 6]]


array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [39]:
# vertical stack the arrays
y = np.array([8, 8, 8])
np.vstack([y, x])

array([[8, 8, 8],
       [1, 2, 3],
       [4, 5, 6]])

In [41]:
# horizotally stack the arrays
y = np.array([[8], [8]])
np.hstack([x, y])

array([[1, 2, 3, 8],
       [4, 5, 6, 8]])

In [43]:
# array splitting operations via np.split
x = [1 ,2, 3, 99, 99, 3, 2, 1]
a1, a2, a3 = np.split(x, [3, 5])
print(a1, a2, a3)


[1 2 3] [99 99] [3 2 1]


In [45]:
# array splitting operations via np.vsplit
grid = np.arange(16).reshape((4,4))
print("Grid: ", grid)

upper, lower = np.vsplit(grid, [2])
print("Upper: ", upper)
print("Lower: ", lower)

Grid:  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Upper:  [[0 1 2 3]
 [4 5 6 7]]
Lower:  [[ 8  9 10 11]
 [12 13 14 15]]


In [46]:
# array splitting operations via np.hsplit
left, right = np.vsplit(grid, [2])
print("Left: ", left)
print("Right: ", right)

Left:  [[0 1 2 3]
 [4 5 6 7]]
Right:  [[ 8  9 10 11]
 [12 13 14 15]]
