# Aggregations

In [1]:
import numpy as np

In [2]:
# Summing the values in array 
x = np.random.random(100)
np.sum(x)

47.967345047442343

In [4]:
# Min and Max 
print("Min value: ", np.min(x))
print("Max value: ", np.max(x))

Min value:  0.0049525467757
Max value:  0.990946158626


In [5]:
M = np.random.random((3,4))
print(M)

[[ 0.04439417  0.02350282  0.10349289  0.52232761]
 [ 0.01339141  0.49762198  0.99392436  0.32668763]
 [ 0.66493567  0.35311175  0.83219309  0.15653336]]


In [6]:
M.sum()

4.5321167458256504

In [7]:
M.min()

0.013391413800862173

In [8]:
M.min(axis=0) # along the columns 

array([ 0.01339141,  0.02350282,  0.10349289,  0.15653336])

In [9]:
M.min(axis=1) # along the rows

array([ 0.02350282,  0.01339141,  0.15653336])

In [12]:
M.max(axis=0)

array([ 0.66493567,  0.49762198,  0.99392436,  0.52232761])

In [13]:
M.max(axis=1)

array([ 0.52232761,  0.99392436,  0.83219309])

In [15]:
M = np.arange(1,10).reshape((3,3))
print(M)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [18]:
print("Sum of elements      np.sum(M)   :", np.sum(M))
print("Product of elements  np.prod(M)  :", np.prod(M))
print("Mean of elements     np.mean(M)  :", np.mean(M))
print("Standard deviation   np.std(M)   :", np.std(M))
print("Variance             np.var(M)   :", np.var(M))
print("Min Value            np.min(M)   :", np.min(M))
print("Max Value            np.max(M)   :", np.max(M))
print("Index of min value   np.argmin(M):", np.argmin(M))
print("Index of max value   np.argmax(M):", np.argmax(M))
print("Median               np.median(M):", np.median(M))
print("Rank based statistics of elements np.percentile(M):", np.percentile(M, q=.5) )
print("Evaluate whether any elements are true  np.any(M):", np.any(M))
print("Evaluate whether all elements are true np.all(M):", np.all(M))

Sum of elements      np.sum(M)   : 45
Product of elements  np.prod(M)  : 362880
Mean of elements     np.mean(M)  : 5.0
Standard deviation   np.std(M)   : 2.58198889747
Variance             np.var(M)   : 6.66666666667
Min Value            np.min(M)   : 1
Max Value            np.max(M)   : 9
Index of min value   np.argmin(M): 0
Index of max value   np.argmax(M): 8
Median               np.median(M): 5.0
Rank based statistics of elements np.percentile(M): 1.04
Evaluate whether any elements are true  np.any(M): True
Evaluate whether all elements are true np.all(M): True
