# Broadcasting

In [1]:
import numpy as np

In [4]:
# Adding a two-dimensional array to a one-dimensional array
M = np.ones((2,3))
x = np.arange(3)

print("M: ", M)
print("x: ", x)

print("Shape of M: ", M.shape)
print("Shape of a: ", x.shape)

result = M + x
print("Result: ", result)
print("Shape of result: ", result.shape)


M:  [[ 1.  1.  1.]
 [ 1.  1.  1.]]
x:  [0 1 2]
Shape of M:  (2, 3)
Shape of a:  (3,)
Result:  [[ 1.  2.  3.]
 [ 1.  2.  3.]]
Shape of result:  (2, 3)


In [6]:
a = np.arange(3)
b = np.arange(3)[:, np.newaxis]
print("a :", a)
print("b :", b)
print("Shape of a: ", a.shape)
print("Shape of b: ", b.shape)

a+b

a : [0 1 2]
b : [[0]
 [1]
 [2]]
Shape of a:  (3,)
Shape of b:  (3, 1)


array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [11]:
# centering an array via broadcasting
M = np.random.random((10,3))
print(M)
print("\n")


M_mean = M.mean(0)
print(M_mean)
print("\n")
M_centered = M - M_mean
print(M_centered)

[[ 0.9606346   0.24523743  0.65646832]
 [ 0.24737808  0.9760433   0.69580224]
 [ 0.71019034  0.6876264   0.06252497]
 [ 0.08977847  0.63441762  0.70452509]
 [ 0.81631548  0.86019427  0.63874566]
 [ 0.91168766  0.73327774  0.04002083]
 [ 0.36241397  0.91878132  0.1098613 ]
 [ 0.21258938  0.66578683  0.40200139]
 [ 0.5246535   0.22319485  0.22439071]
 [ 0.95845153  0.39199701  0.74677985]]


[ 0.5794093   0.63365568  0.42811204]


[[ 0.3812253  -0.38841824  0.22835629]
 [-0.33203122  0.34238762  0.26769021]
 [ 0.13078104  0.05397073 -0.36558707]
 [-0.48963083  0.00076194  0.27641305]
 [ 0.23690617  0.22653859  0.21063362]
 [ 0.33227836  0.09962206 -0.3880912 ]
 [-0.21699533  0.28512564 -0.31825074]
 [-0.36681992  0.03213115 -0.02611065]
 [-0.0547558  -0.41046082 -0.20372132]
 [ 0.37904223 -0.24165867  0.31866781]]
