# Boolean Operations

In [1]:
import numpy as np

In [2]:
x = np.array([1, 2, 3, 4,5])
x < 3

array([ True,  True, False, False, False], dtype=bool)

In [3]:
x > 3

array([False, False, False,  True,  True], dtype=bool)

In [4]:
x <= 3

array([ True,  True,  True, False, False], dtype=bool)

In [5]:
x >= 3

array([False, False,  True,  True,  True], dtype=bool)

In [6]:
x != 3

array([ True,  True, False,  True,  True], dtype=bool)

In [7]:
#  how many values less than 6?
np.count_nonzero(x < 6)

5

In [8]:
np.sum(x < 6)

5

In [16]:
# how many values less than 6 in each row?
x = np.arange(1,10).reshape((3,3))
print(x)
np.sum( x < 5, axis=1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([3, 1, 0])

In [17]:
# are there any value greater than 7?
np.any(x > 7)

True

In [18]:
# are there all values equals to 10?
np.all(x == 10)

False

In [19]:
# are all values in each row less than 10?
np.all(x < 10, axis=1)

array([ True,  True,  True], dtype=bool)

In [20]:
# new array 
y = x[x<5]
y

array([1, 2, 3, 4])